import io
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

from .asset_cache import get_source


FONT = Path(__file__).parent / "assets/fonts/SourceHanSansSC-Bold.otf"
WATERMARK = "Generated By AiriCore"


def add_watermark(payload: bytes) -> bytes:
    with Image.open(io.BytesIO(payload)) as source:
        image = source.convert("RGBA")
    size = max(10, min(28, round(min(image.size) * 0.018)))
    margin = max(6, round(min(image.size) * 0.012))
    font_data = get_source(FONT)
    while True:
        font = ImageFont.truetype(io.BytesIO(font_data), size)
        bounds = font.getbbox(WATERMARK, stroke_width=1)
        if bounds[2] - bounds[0] <= image.width - margin * 2 or size == 1:
            break
        size -= 1
    overlay = Image.new("RGBA", image.size)
    draw = ImageDraw.Draw(overlay)
    draw.text(
        (image.width - margin - bounds[2], image.height - margin - bounds[3]),
        WATERMARK,
        font=font,
        fill=(255, 255, 255, 100),
        stroke_width=1,
        stroke_fill=(0, 0, 0, 70),
    )
    output = io.BytesIO()
    Image.alpha_composite(image, overlay).save(output, "PNG")
    return output.getvalue()
