import io
import json
import math
import unicodedata
from datetime import datetime, timedelta, timezone
from pathlib import Path

from PIL import Image, ImageDraw

from utils.cache import get_font, get_image

from .service import PAGE_SIZE
from .protocol import QueryError
from .settlement_rendering import positioned, render_settlement
from .profile_rendering import (
    paint_achievements,
    paint_character,
    paint_label,
    paint_tabs,
)


ASSETS = Path(__file__).parent / "assets"
NAMES = json.loads((ASSETS / "names.json").read_text(encoding="utf-8"))
CARDS = json.loads((ASSETS / "cards.json").read_text(encoding="utf-8"))
PORTRAITS = json.loads((ASSETS / 'cards/portraits.json').read_text(encoding='utf-8'))
LOCAL_TIME = timezone(timedelta(hours=8))
RESAMPLE = Image.Resampling.LANCZOS
INK = "#24232b"


def _number(value, default=0):
    try:
        return int(value)
    except (TypeError, ValueError, OverflowError):
        return default


def _clean(value):
    return "".join(
        character
        for character in str(value or "")[:4096]
        if character == "\n" or not unicodedata.category(character).startswith("C")
    )


def _image(path):
    return get_image(ASSETS / path).copy()


def _sprite(key, package="AccountInfo"):
    return _image(f"ui/{package}/{key}.png")


def _paste(canvas, image, xy, size=None):
    if size is not None:
        image = image.resize(size, RESAMPLE)
    canvas.alpha_composite(image, tuple(map(int, xy)))


def _background(size):
    canvas = _sprite("kn6fq3y", "Common").resize(size, RESAMPLE)
    _paste(canvas, _sprite("f3tl12"), (20, 20), (size[0] - 40, size[1] - 40))
    return canvas


def _text(canvas, value, box, size=30, color=INK, align="left", minimum=16):
    value = _clean(value).replace("\n", " ")
    left, top, width, height = box
    draw = ImageDraw.Draw(canvas)
    font = get_font(ASSETS / "JingNanBoBoHei.ttf", size)
    while size > minimum and draw.textbbox((0, 0), value, font=font)[2] > width:
        size -= 1
        font = get_font(ASSETS / "JingNanBoBoHei.ttf", size)
    if draw.textlength(value, font=font) > width:
        while value and draw.textlength(value + "…", font=font) > width:
            value = value[:-1]
        value += "…"
    bounds = draw.textbbox((0, 0), value, font=font)
    measured = draw.textlength(value, font=font)
    x = left + (width - measured) / 2 if align == "center" else left
    y = top + (height - bounds[3] + bounds[1]) / 2 - bounds[1]
    draw.text((round(x), round(y)), value, font=font, fill=color)


def _wrap(value, width, size=28):
    font = get_font(ASSETS / "JingNanBoBoHei.ttf", size)
    lines = []
    for paragraph in _clean(value).split("\n"):
        line = ""
        for character in paragraph:
            if line and font.getlength(line + character) > width:
                lines.append(line)
                line = ""
            line += character
        lines.append(line)
    return lines


def _png(canvas):
    canvas = canvas.convert("RGBA")
    label = "Generated By AiriCore"
    size = max(10, min(22, round(min(canvas.size) * 0.018)))
    margin = max(6, round(min(canvas.size) * 0.012))
    font = get_font(ASSETS / "Impact.ttf", size)
    bounds = font.getbbox(label, stroke_width=1)
    overlay = Image.new("RGBA", canvas.size)
    ImageDraw.Draw(overlay).text(
        (canvas.width - margin - bounds[2], canvas.height - margin - bounds[3]),
        label,
        font=font,
        fill=(255, 255, 255, 96),
        stroke_width=1,
        stroke_fill=(0, 0, 0, 64),
    )
    canvas = Image.alpha_composite(canvas, overlay)
    result = io.BytesIO()
    canvas.convert("RGB").save(result, format="PNG", optimize=True)
    return result.getvalue()


def _hero(hero_id):
    return NAMES["heroes"].get(
        str(hero_id), f"角色 {_number(hero_id)}" if hero_id else "未提供角色"
    )


def _mode(mode_id):
    return NAMES["modes"].get(
        str(mode_id), f"模式 {_number(mode_id)}" if mode_id else "未提供模式"
    )


def _time(timestamp):
    try:
        value = int(timestamp)
        if value <= 0:
            return "时间未提供"
        return datetime.fromtimestamp(value, LOCAL_TIME).strftime("%Y-%m-%d %H:%M")
    except (ValueError, TypeError, OverflowError, OSError):
        return "时间未提供"


def _identity(snapshot):
    info = snapshot.get("info") or {}
    return (
        info.get("name") or "未提供昵称",
        info.get("lv"),
        str(snapshot.get("uid", "—")),
    )


def _header(canvas, title, snapshot, width=1280):
    name, level, uid = _identity(snapshot)
    _paste(canvas, _sprite("f3tl16"), (60, 50), (width - 120, 132))
    _text(canvas, title, (90, 64, width - 180, 45), 38)
    _text(canvas, name, (90, 120, width - 630, 38), 28)
    _text(canvas, f"UID：{uid}", (width - 480, 120, 390, 38), 24, align="center")


def render_message(title, lines):
    if isinstance(lines, str):
        lines = [lines]
    wrapped = []
    for line in list(lines)[:40]:
        wrapped.extend(_wrap(line, 1050))
        wrapped.append("")
    wrapped = wrapped[:44]
    while wrapped and not wrapped[-1]:
        wrapped.pop()
    height = max(500, math.ceil((155 + 43 * len(wrapped)) / 0.85) + 120)
    canvas = _background((1280, height))
    _paste(canvas, _sprite("f3tl16"), (60, 60), (1160, height - 120))
    _text(canvas, title, (110, 86, 1060, 66), 44)
    for index, line in enumerate(wrapped):
        _text(canvas, line, (110, 176 + index * 43, 1050, 40), 28)
    return _png(canvas)


def render_profile(snapshot):
    canvas = _sprite("kn6fq3y", "Common").resize((1920, 1080), RESAMPLE)
    _paste(canvas, _sprite("f3tl12"), (390, 98))
    painting_notice = paint_character(canvas, snapshot)
    _paste(canvas, _sprite("f3tl1c"), (964, 108))
    paint_tabs(canvas)
    show = snapshot.get("show") or {}
    statistics = show.get("statistics") or {}
    if not show.get("isShowData"):
        _text(canvas, "该玩家未公开统计资料", (1085, 318, 365, 60), 30, align="center")
    elif not statistics:
        _text(canvas, "暂无统计资料", (1085, 318, 365, 60), 30, align="center")
    else:
        _paste(canvas, _sprite("it6m2u"), (1063, 175))
        fields = (
            ("累计参与局数", "fightCount"),
            ("累计胜利局数", "winFightCount"),
            ("拥有角色数量", "roleCardCount"),
            ("最常用角色", "useHero"),
            ("拥有装扮数量", "adornCount"),
            ("拥有皮肤数量", "skinCount"),
        )
        for index, (label, key) in enumerate(fields):
            value = statistics.get(key)
            value = (
                _hero(value)
                if key == "useHero" and value
                else "—"
                if value is None
                else str(value)
            )
            _text(
                canvas,
                f"{label}：{value}",
                (1085, (181, 248, 315, 380, 447, 509)[index], 346, 44),
                30,
                "black",
            )
    _paste(canvas, _sprite("m1i721"), (1015, 574), (48, 48))
    _paste(canvas, _sprite("m1i722"), (1015, 574), (48, 48))
    _text(canvas, str(show.get("praiseNum", "—")), (1064, 574, 174, 49), 36, "black")
    _paste(canvas, _sprite("f3tl16"), (872, 721))
    label_notice = paint_label(canvas, snapshot)
    paint_achievements(canvas, snapshot)
    if painting_notice:
        _text(canvas, painting_notice, (450, 460, 500, 50), 28, "white", align="center")
    if label_notice:
        _text(canvas, label_notice, (1200, 685, 300, 32), 22, "#66636f")
    return _png(canvas.crop((360, 75, 1642, 967)))


def render_records(snapshot, page=1):
    if not isinstance(page, int) or isinstance(page, bool) or page < 1:
        raise ValueError("战绩页码应为正整数")
    show = snapshot.get("show") or {}
    if not show.get("isShowFight"):
        return render_message("近期战绩", ["该玩家未公开对局记录"])
    records = show.get("record") or []
    pages = max(1, math.ceil(len(records) / PAGE_SIZE))
    if page > pages:
        raise ValueError(f"战绩仅有 {pages} 页")
    if not records:
        return render_message("近期战绩", ["暂无公开对局记录"])
    canvas = _background((1280, 930))
    _header(canvas, "近期战绩", snapshot)
    _paste(canvas, _sprite("f3tl16"), (60, 206), (1160, 645))
    _text(canvas, "序号        对局时间 / 模式", (105, 218, 590, 38), 23, "#625e6d")
    _text(canvas, "名次", (735, 218, 120, 38), 23, "#625e6d", align="center")
    _text(canvas, "使用角色", (891, 218, 250, 38), 23, "#625e6d", align="center")
    start = (page - 1) * PAGE_SIZE
    for index, row in enumerate(records[start : start + PAGE_SIZE]):
        y = 271 + index * 86
        _paste(canvas, _sprite("f3tl1i"), (90, y), (1100, 79))
        _text(
            canvas,
            f"{start + index + 1:02d}",
            (107, y + 12, 65, 51),
            32,
            "white",
            align="center",
        )
        _text(canvas, _time(row.get("time")), (193, y + 2, 480, 37), 25, "white")
        _text(canvas, _mode(row.get("mapType")), (193, y + 39, 480, 33), 23, "#f4f0f7")
        rank = _number(row.get("rank"))
        _text(
            canvas,
            f"第 {rank} 名" if rank > 0 else "未提供",
            (730, y + 12, 130, 51),
            25,
            align="center",
        )
        _text(
            canvas, _hero(row.get("heroId")), (895, y + 12, 255, 51), 25, align="center"
        )
    _text(
        canvas,
        f"第 {page} / {pages} 页 · 共 {len(records)} 场",
        (80, 833, 1120, 42),
        25,
        "white",
        align="center",
    )
    return _png(canvas)


def render_detail(snapshot):
    show = snapshot.get("show") or {}
    if not show.get("isShowFight"):
        return render_message("对局详情", ["该玩家未公开对局记录"])
    details = snapshot.get("details") or []
    if not details:
        return render_message("对局详情", ["暂无该对局的公开详情"])
    selected = snapshot.get("selected") or {}
    canvas = render_settlement(
        snapshot, _mode(selected.get("mapType")), _time(selected.get("time"))
    )
    return _png(canvas)


def render_notice(title, lines):
    return render_message(title, lines)


def render_hands(snapshot):
    from .card_rendering import group_cards, render_card
    players = snapshot['players']
    columns, card_w, card_h, row_h = 5, 200, 293, 316
    sections = []
    for player in players:
        groups = group_cards(player['cards'], player, snapshot.get('map_type', 4))
        sections.append((player, groups, 100 + (math.ceil(len(groups) / columns) * row_h if groups else 88)))
    height = 230 + sum(size + 20 for _, _, size in sections)
    if height > 4800:
        raise QueryError('本次手牌数量超过图片展示上限，请稍后重试或联系管理员')
    canvas = _sprite('kn6fq3y', 'Common').resize((1280, height), RESAMPLE)
    canvas = Image.alpha_composite(canvas, Image.new('RGBA', canvas.size, (13, 16, 29, 220)))
    draw = ImageDraw.Draw(canvas)
    _text(canvas, f'玩家手牌预览 · 观战码 {snapshot.get("watch_code") or "未提供"}', (54, 32, 1170, 58), 38, '#f5f3ff')
    _text(canvas, f'{_mode(snapshot["map_type"])} · 第 {snapshot["round"]} 回合', (54, 94, 800, 36), 25, '#d2c8ef')
    captured = datetime.fromtimestamp(snapshot['captured_at'], LOCAL_TIME).strftime('%Y-%m-%d %H:%M:%S')
    _text(canvas, f'快照 {captured}', (835, 94, 390, 36), 21, '#c4bdd7', align='center')
    y = 154
    accents = ('#bca4ff', '#80d7ee', '#f3b383', '#a6d59d')
    for player, groups, section_height in sections:
        draw.rounded_rectangle((34, y, 1246, y + section_height), radius=20, fill='#25283b', outline='#43465e', width=1)
        draw.rounded_rectangle((54, y + 22, 60, y + 59), radius=3, fill=accents[player['slot'] % 4])
        rank_key = ('qees2g', 'qees2h', 'qees2i', 'qees2f')[player['slot']]
        rank = _image(f'settlement/BattleSettlement/{rank_key}.png')
        rank = rank.crop(rank.getbbox())
        rank.thumbnail((66, 50), RESAMPLE)
        _paste(canvas, rank, (74, y + 11 + (50 - rank.height) // 2))
        portrait_path = PORTRAITS.get(str(player['hero_id']))
        if portrait_path:
            portrait = _image(portrait_path)
            portrait = portrait.crop(portrait.getbbox())
            portrait.thumbnail((60, 60), RESAMPLE)
            _paste(canvas, portrait, (151 + (60 - portrait.width) // 2, y + 7 + (60 - portrait.height) // 2))
        _text(canvas, f'{player["name"]} · {_hero(player["hero_id"])}', (229, y + 16, 687, 46), 28, '#f7f6fc')
        hidden = sum(card.get('id') is None for card in player['cards'])
        unknown = sum(card.get('id') is not None and str(card['id']) not in CARDS for card in player['cards'])
        summary = f'手牌 {len(player["cards"])} 张'
        if hidden:
            summary += f' · 不可见 {hidden}'
        if unknown:
            summary += f' · 未收录 {unknown}'
        _text(canvas, summary, (934, y + 21, 286, 36), 22, '#d2cde3', align='center')
        draw.line((56, y + 70, 1224, y + 70), fill='#45475e', width=1)
        for index, (card, count) in enumerate(groups):
            image = render_card(card, player, snapshot['map_type'])
            x, top = 62 + index % columns * 234, y + 88 + index // columns * row_h
            scaled, xy = positioned(image, {'x': x, 'y': top, 'scale': (card_w / 440, card_h / 644)})
            canvas.alpha_composite(scaled, xy)
            if count > 1:
                label = f'x{count}'
                font = get_font(ASSETS / 'Impact.ttf', 54)
                bounds = draw.textbbox((0, 0), label, font=font, stroke_width=4)
                draw.text((x + card_w + 24 - bounds[2], top + card_h - bounds[3]), label,
                          font=font, fill='#ffffff', stroke_width=4, stroke_fill='#000000')
        if not player['cards']:
            _text(canvas, '当前没有手牌', (62, y + 92, 1156, 60), 28, '#c4bdd7', align='center')
        y += section_height + 20
    _text(canvas, 'PVE 观战快照 · 隐藏及未收录牌面显示为卡背', (54, height - 62, 1156, 34), 20, '#c4bdd7', align='center')
    return _png(canvas)


def render_help():
    return render_message(
        "AiriCore 星趴查询 · 帮助",
        [
            "astral help  ·  查看本帮助",
            "astral bind UID  ·  绑定账号",
            "astral unbind  ·  解绑账号",
            "astral me  ·  查看你的公开资料",
            "astral UID  ·  查看指定玩家的公开资料",
            "astral me recent  ·  你的近期战绩",
            "astral me recent 页码  ·  查看你的近期战绩第N页",
            "astral UID recent  ·  指定玩家的近期战绩（加页码同上）",
            "astral me battle 序号  ·  你第N号对局的对局详情",
            "astral UID battle 序号  ·  指定玩家的对局详情",
            "astral watch 观战码  ·  设置当前群的观战对局（仅群聊）",
            "astral card  ·  查看本群对局当前可见手牌（仅群聊）",
            "astral unwatch  ·  停止当前群观战（仅群聊）",
            "astral status  ·  查看绑定与查询账号配置状态",
            "* UID、页码和序号请替换为实际数字",
        ],
    )
